- name: install httpd package (CentOS)
  tags: 
    - apache
    - centos
    - httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: install apache2 package (Debian)
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: copy html file for default apache site
  tags: 
    - apache
    - apache2
    - httpd
  ansible.builtin.copy:
    src: ~/ansible_tutorial/ansible-tutorial/files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change log level in apache2.conf
  tags: apache,debian,httpd
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^LogLevel warn'
    line: LogLevel notice
  when: ansible_distribution == "Debian"
  register: apache2

- name: restart httpd (Debian)
  tags: apache,debian,httpd
  service:
    name: apache2
    state: restarted
  when: apache2.changed