---
- hosts: localhost
  connection: local
  become: true

  pre-tasks:
    - name: update repositories
      tags: always
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
  tasks:
    - include: tasks/packages.yaml