- name: install packages
  ansible.builtin.apt:
    name: 
      - htop
      - tmux
      - mc
      - cron

- name: start cron deamon
  ansible.builtin.service:
    name: cron
    state: started