apache_package_name: httpd
apache_service: httpd
php_package_name: php
mariadb_package_name: mariadb
terraform_zip_url: https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip