- name: add ssh key for simone
  tags:
    - ssh_keys
  ansible.posix.authorized_key:
    user: simone
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: openssh | generate sshd_config file from template
  tags: ssh_config
  ansible.builtin.template:
    src: "{{ fetch_ssh_config_dest }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s
  notify: restart_ssh